const CASES_DATA = [
    {
        title: "Mr Thomas Allen -v- Oolong Ltd",
        citation: "Case No: 6027054/2025",
        date: "",
        type: "",
        confidential: "",
        court: "London South Employment Tribunal",
        judge: "Employment Judge Walker",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Successful Final Hearing. The Tribunal found unlawful deductions of £29,166.66. While the Respondent alleged an oral agreement to reduce salary, the Tribunal applied <em>Kerr v The Sweater Shop</em> and <em>International Packaging v Balfour</em> to rule that, absent written notification of the variation terms <em>before</em> the deduction, the deductions violated s.13(2)(b) ERA 1996. The Tribunal further applied <em>Agnew</em> to establish a 'series of deductions' despite gaps in payment, preserving the full claim period.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss C Waller -v- Sanctuary Housing Association",
        citation: "Case No: 6007283/2025",
        date: "",
        type: "",
        confidential: "",
        court: "West Midlands Employment Tribunal",
        judge: "Employment Judge Jones",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing for case management.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr O Sanodze -v- EV Downton Ltd & Others",
        citation: "Case No: 716043",
        date: "",
        type: "",
        confidential: "",
        court: "Bristol Employment Tribunal",
        judge: "Employment Judge Chudleigh",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing fixture involving multiple respondents (Wincanton PLC, XPO Logistics).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ms Gill Grant -v- Financial Ombudsman Service Ltd",
        citation: "Case No: 703244",
        date: "",
        type: "",
        confidential: "",
        court: "East London Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Agbotey v Maier UK Ltd",
        citation: "Case No: 6009509/2025",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal (Midlands West)",
        judge: "Employment Judge Wedderspoon",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Successfully defended claims valued at £44,000 arising from the summary dismissal of a senior operator for gross negligence. The Tribunal found the dismissal fair following a 'shock-loading' incident involving a 13-tonne crane tool and a failure to follow mandatory reporting procedures.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr D Love -v- Mitie Group PLC",
        citation: "Case No: 725013",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal",
        judge: "Employment Judge P Davies",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Neesha Hosein-Tang How -v- Shell UK Limited",
        citation: "Case No: 725420",
        date: "",
        type: "",
        confidential: "",
        court: "Glasgow Employment Tribunal",
        judge: "Employment Judge Smail",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing regarding jurisdiction and case management.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "J Asselman -v- Serco & Others",
        citation: "Case No: 1304744/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Robin Broughton",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing involving individual named respondents (Jo Doherty, Ian Moss).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Amy Peel -v- Symons, Gay & Leland LLP",
        citation: "Case No: 6021916/2024",
        date: "",
        type: "",
        confidential: "",
        court: "East London Employment Tribunal",
        judge: "Employment Judge Robertson",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing involving partnership dispute.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Sandra Harding & Others -v- Birmingham City Council",
        citation: "Case No: 1304212/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Frances Eccles",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Case Management Preliminary Hearing involving multiple claimants against the Local Authority and Local Enterprise Partnership.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Christine Morgan & Stephen Lewis -v- Inductotherm Europe Limited",
        citation: "Case No: 1308843/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge B J Clarke",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing for consolidated claims.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "S Nowondy & Others -v- Delta Academies Trust",
        citation: "Case No: 1800378/2022",
        date: "",
        type: "",
        confidential: "",
        court: "Leeds Employment Tribunal",
        judge: "Employment Judge Buckley",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing for multiple claimant action.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss P Hung -v- JLL",
        citation: "Case No: 3200939/2024",
        date: "",
        type: "",
        confidential: "",
        court: "East London Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Timothy Dore -v- IDS Transport (UK) LTD",
        citation: "Case No: 711413",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Buckley",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss M Bradley -v- Senad Community LTD",
        citation: "Case No: 2603299/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Leicester Employment Tribunal",
        judge: "Employment Judge Dunlop",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "E Robertson -v- Mitie Limited",
        citation: "Case No: 8001143/2025",
        date: "",
        type: "",
        confidential: "",
        court: "Glasgow Employment Tribunal",
        judge: "Employment Judge JM Wade",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Stephen John Watters -v- Bluebird Care Franchises Limited",
        citation: "Case No: 6005593/2025",
        date: "",
        type: "",
        confidential: "",
        court: "Bristol Employment Tribunal",
        judge: "Employment Judge Lucy Wiseman",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "K Townsend -v- Paper London Limited",
        citation: "Case No: 3307137/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge Pirani",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Lee Robinson -v- Stephen John Williams TA/ National Property Buyers",
        citation: "Case No: 1303573/2025",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal (Midlands West)",
        judge: "Employment Judge Wedderspoon",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Breach of Contract / Unlawful Deductions in relation to commission payments.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Margaret Anne Sullivan -v- H M Courts and Tribunal Services",
        citation: "Case No: 6015344/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Matthews",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Liz Dobson -v- Berkshire Healthcare NHS Foundation Trust",
        citation: "Case No: 33052241/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge Harper MBE",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing regarding jurisdictional issues.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ms Victoria Fairbairn -v- PS Forwarding Co Ltd",
        citation: "Case No: 3302615/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge Pirani",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing to determine case management orders.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss Jacqueline Keddie Kelsall -v- Betsi Cadwaladr University Health Board",
        citation: "Case No: 1604319/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Wales Employment Tribunal",
        judge: "EJ Lloyd-Lawrie",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Open Preliminary Hearing to determine disability status under the Equality Act 2010.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Nazia Bi -v- (1) Jane Tovery (2) University City Hospital of Birmingham",
        citation: "Case No: 1303877/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Harding",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing to identify issues in complex multi-respondent claim.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Andrew Garland v Footfalls and Heartbeat (UK) Limited",
        citation: "Case No: 2600511/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Nottingham Employment Tribunal",
        judge: "Employment Judge Shepherd",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Susie Thompson -v- Gentoo Group",
        citation: "Case No: 6013987/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Newcastle Employment Tribunal",
        judge: "Employment Judge Bright",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing/Mediation.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mrs Asia Mahmood -v- Dawat e Islami UK",
        citation: "Case No: 6025015/2025",
        date: "",
        type: "",
        confidential: "",
        court: "Leeds Employment Tribunal",
        judge: "Employment Judge S Shore",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (3 days).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Dawn Dickson -v- ASDA",
        citation: "Case No: 8001991/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Glasgow Employment Tribunal",
        judge: "Employment Judge Pirani",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Case Management Preliminary Hearing via CVP.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mrs M Karch v Unipart Group Ltd",
        citation: "Case No: 1304180/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal (Midlands West)",
        judge: "EJ ",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Multi-week disability discrimination claim.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "John Lowe v Keble Heath Construction",
        citation: "Case No: 1300123/2025",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal",
        judge: "EJ Smith",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Successfully defended claims of automatic unfair dismissal and whistleblowing detriment. Secured the withdrawal of all claims following the conclusion of the Claimant's evidence.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mark Roberts -v- Cast Iron Welding Services Limited",
        citation: "Case No: 6018151/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Leicester Employment Tribunal",
        judge: "Employment Judge Brace",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (4 days).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Professor Peter Lax -v- The United Lincolnshire Hospitals NHS Trust",
        citation: "Ref: 568MC635",
        date: "",
        type: "",
        confidential: "",
        court: "Lincoln County Court",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (1 day).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mrs D Johnson V Prysmian Cables & Systems Ltd",
        citation: "Case No: 1300070/2024",
        date: "",
        type: "",
        confidential: "",
        court: "West Midlands Employment Tribunal",
        judge: "EJ Edmonds",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (10 days).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Paul Bryson -v- Schneider Electric UK Ltd",
        citation: "Case No: 715878",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing for Case Management.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Nina Ogilvie -v- Alexander Optometrists",
        citation: "Case No: 6013922/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Newcastle Employment Tribunal",
        judge: "Employment Judge Gould",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (3 days).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr O Sanodze -v- EV Downton Ltd",
        citation: "Case No: 716043",
        date: "",
        type: "",
        confidential: "",
        court: "Bristol Employment Tribunal",
        judge: "Employment Judge Chudleigh",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing fixture regarding whistleblowing claims.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Umran Suleman -v- Maximus UK Services Limited",
        citation: "Case No: 713582",
        date: "",
        type: "",
        confidential: "",
        court: "Leeds Employment Tribunal",
        judge: "Employment Judge Warren",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing on case management and potential strike out.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss C Ettore -v- Pro Support Limited",
        citation: "Case No: 714386",
        date: "",
        type: "",
        confidential: "",
        court: "Manchester Employment Tribunal",
        judge: "Employment Judge Leach",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Conference/PH prior to Final Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "J Asselman -v- Serco & Others",
        citation: "Case No: 707884",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Robin Broughton",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing involving multiple named respondents (Jo Doherty, Ian Moss).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ms A Khambay -v- George Eliot Hospital NHS Trust",
        citation: "Case No: 708410",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing involving NHS Trust.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Christine Morgan & Stephen Lewis -v- Inductotherm Europe Limited",
        citation: "Case No: 703539",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge B J Clarke",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing for multiple claimants.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "S Nowondy & Others -v- Delta Academies Trust",
        citation: "Case No: 702029",
        date: "",
        type: "",
        confidential: "",
        court: "Leeds Employment Tribunal",
        judge: "Employment Judge Buckley",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing involving multiple claimants.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss P Hung -v- JLL",
        citation: "Case No: 712257",
        date: "",
        type: "",
        confidential: "",
        court: "East London Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Sandra Harding & Others -v- Birmingham City Council",
        citation: "Case No: 1304212/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Frances Eccles",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing involving the City Council.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Timothy Dore -v- IDS Transport (UK) LTD",
        citation: "Case No: 711413",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Buckley",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss M Bradley -v- Senad Community LTD",
        citation: "Case No: 712202",
        date: "",
        type: "",
        confidential: "",
        court: "Leicester Employment Tribunal",
        judge: "Employment Judge Dunlop",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "F. Manshausen v IMI Precision Engineering",
        citation: "Case No: 1310744/2022",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Perry",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Successfully represented the Claimant in a multi-day liability hearing. The Tribunal found the Claimant was unfairly dismissed and victimised following his grievance regarding the devaluation of his role upon returning from cancer-related absence. The redundancy process was found to be a sham.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "K Townsend -v- Paper London Limited",
        citation: "Case No: 710385",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge Pirani",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Francis Enahoro -v- ASDA Stores Ltd",
        citation: "Case No: 706996",
        date: "",
        type: "",
        confidential: "",
        court: "London South Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing (Case Management).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ion Burca -v- MD Construction",
        citation: "Case No: 6000185/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Leeds Employment Tribunal",
        judge: "Employment Judge B Beyzade",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing (Video) for Case Management.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Elaine Martin -v- Care Ashore",
        citation: "Case No: 710460",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge Postle",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Parvinder Hammonds -v- HRS Family Law Solicitors Ltd",
        citation: "Case No: 701136",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Grubb",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing and Judicial Mediation.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mukesh Pawar -v- Jaguar Land Rover Ltd",
        citation: "Case No: 701853",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge J Connolly",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing regarding complex discrimination claims.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Terri-Anne Large -v- ASDA Stores Limited",
        citation: "Case No: 708586",
        date: "",
        type: "",
        confidential: "",
        court: "Nottingham Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Melanie Chandler -v- The King's Fund",
        citation: "Case No: 709512",
        date: "",
        type: "",
        confidential: "",
        court: "London Central Employment Tribunal",
        judge: "Employment Judge",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing (Video).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Shaun Wood -v- Rolleston Park Farm",
        citation: "Case No: 708968",
        date: "",
        type: "",
        confidential: "",
        court: "Nottingham Employment Tribunal",
        judge: "Employment Judge M Kearns",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing regarding farm employment dispute.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "John Bradley -v- Technical Drive",
        citation: "Case No: 6019242/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge E Fowell",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (4 days).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss C Ettore -v- Pro Support Limited",
        citation: "Case No: 2402575/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Manchester",
        judge: "Employment Judge Leach",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Miss C Ettore brought claims against Pro Support Limited including unfair dismissal, detriments, and unauthorized deductions from wages. The tribunal dismissed the unfair dismissal claims as they were presented out of time and it was reasonably practicable to present them earlier. The claims relating to detriments and unauthorized wage deductions were allowed to proceed to further case management.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ms A Khambay -v- George Eliot Hospital NHS Trust",
        citation: "Case No: 708410",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing involving NHS Trust.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Daisy Lo -v- Norfolk and Suffolk NHS Foundation Trust",
        citation: "Case No: 707529",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge Adkinson sitting alone",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Case Management Preliminary Hearing (Video).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "CN Hall -v- Do & Co International Catering Ltd",
        citation: "Case No: 707755",
        date: "",
        type: "",
        confidential: "",
        court: "Bristol Employment Tribunal",
        judge: "Employment Judge Russell",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ebony Laleye -v- ASDA Stores Limited",
        citation: "Case No: 695080",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss C Stewart -v- Hypebeast UK Ltd",
        citation: "Case No: 691835",
        date: "",
        type: "",
        confidential: "",
        court: "London Central Employment Tribunal",
        judge: "Employment Judge Woffenden",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing regarding jurisdictional points.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mrs Nichola Pilgrim -v- Herefordshire and Worcestershire Health and Care NHS Trust",
        citation: "Case No: 691775",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Harrington",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Fay Bryant -v- Brays School",
        citation: "Case No: 706597",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Phil Allen",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "I Beckett -v- Weetabix Limited",
        citation: "Case No: 706357",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge JM Wade",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Rachel McDonald -v- Avanti Schools Trust",
        citation: "Case No: 2601646/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Leicester Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing to determine case management orders.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Habila Tikon -v- (1) Mitie Limited (2) Her Majestys Revenue and Customs",
        citation: "Ref: EA-2023-000125-AT",
        date: "",
        type: "",
        confidential: "",
        court: "London Central by CVP on 16 December 2022",
        judge: "Employment Judge Hindmarch",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The tribunal struck out all claims against HMRC and the claimant's unfair dismissal and detriment claims as out of time, allowing only the unlawful deduction from wages and breach of contract claims to proceed against Mitie Limited.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Marta Grobarcikova Gonczyova -v- Barchester Healthcare Ltd",
        citation: "Case No: 2205716/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Bristol by CVP",
        judge: "Employment Judge Walters",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Mrs. Marta Grobarcikova Gonczyova brought claims against Barchester Healthcare Ltd alleging disability discrimination arising under section 15 of the Equality Act 2010 and failure to make reasonable adjustments under section 21. The Tribunal found that although the claimant was disabled, the alleged unfavourable treatment and failure to make reasonable adjustments claims were not made out and dismissed both claims.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Z v HRS Family Law Solicitors Ltd",
        citation: "Case No: 1303456/2024",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal",
        judge: "EJ Edmonds",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Acted for the Respondent law firm in a sensitive disability discrimination claim arising from the performance management of a solicitor suffering from alcoholism.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Rachel Webb -v- The University of Worcester",
        citation: "Case No: 700105",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Gray",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Nazia Bi -v- Jane Tovery",
        citation: "Case No: 705149",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Harding",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "M Lewis -v- Interduct Uk Ltd",
        citation: "Case No: 702658",
        date: "",
        type: "",
        confidential: "",
        court: "Reading Employment Tribunal",
        judge: "Employment Judge Manley",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Raymond Gibbons -v- John Lewis Plc",
        citation: "Case No: 2301957/2022",
        date: "",
        type: "",
        confidential: "",
        court: "Ashford Employment Tribunal",
        judge: "Employment Judge Webster",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr H Taha -v- Novatek Europe Ltd",
        citation: "Case No: 701880",
        date: "",
        type: "",
        confidential: "",
        court: "London South Employment Tribunal",
        judge: "Employment Judge E Fowell",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Hasnain Visram -v- Boots Management Services Ltd",
        citation: "Case No: TBC",
        date: "",
        type: "",
        confidential: "",
        court: "London Central Employment Tribunal",
        judge: "Employment Judge Heap",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (4 days).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "A Medina -v- PRODENT LONDON LTD",
        citation: "Case No: 2209044/2022",
        date: "",
        type: "",
        confidential: "",
        court: "London Central Employment Tribunal",
        judge: "Employment Judge Webster",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Dr A Medina brought a claim against Prodent London Ltd for unlawful deductions from wages under section 13 of the Employment Rights Act 1996. The tribunal found that the employer made unauthorised deductions from the claimant’s pay in May, June, and July 2022, which were not authorised by statute, contract, or the claimant’s prior written consent, and ordered the respondent to pay £29,384.40 in gross sums to the claimant.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Luke Salter -v- Muller UK & Ireland Group LLP",
        citation: "Case No: 1304966/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Dimbylow",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The claimant, Mr Luke Salter, brought a claim for constructive unfair dismissal against his employer, Muller UK & Ireland Group LLP. The Employment Tribunal found that the claim was not well-founded and dismissed it, concluding that the claimant had not established constructive unfair dismissal.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Alex John Boggs -v- Warrington & Halton Hospitals Foundation",
        citation: "Case No: 2402734/2022",
        date: "",
        type: "",
        confidential: "",
        court: "Liverpool Employment Tribunal",
        judge: "Employment Judge Aspinall",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The claimant, John William Kennedy Boggs, brought claims against Warrington and Halton Teaching Hospitals NHS Foundation Trust for unfair dismissal, wrongful dismissal, and disability discrimination arising from autism, anxiety, and depression. The Tribunal found in favor of the respondent on unfair dismissal, wrongful dismissal, discrimination arising from disability, and harassment claims, but partially upheld the claim for failure to make reasonable adjustments.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Akeem Adesola -v- (1) Mitie (2) Kingdom Services Group",
        citation: "Case No: 2204229/2021",
        date: "",
        type: "",
        confidential: "",
        court: "London Central Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (1 day).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Anahita Ansari -v- Prodent London Limited",
        citation: "Case No: 2201830/2023",
        date: "",
        type: "",
        confidential: "",
        court: "London Central (in public, by video)",
        judge: "Employment Judge Klimov",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The claimant, Ms Anahita Ansari, brought multiple complaints against Prodent London Limited which were heard over several days in a London Central Employment Tribunal. The tribunal found that none of the claimant’s complaints were well-founded and consequently dismissed the claim in full.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Finbarr J Conolly -v- Radiocoms Systems Ltd",
        citation: "Case No: 701586",
        date: "",
        type: "",
        confidential: "",
        court: "Manchester Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Tonia Couzins -v- HEREFORDSHIRE CITY COUNCIL",
        citation: "Case No: 701432",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "E Barrance -v- Sanderson Design Group Brands Limited",
        citation: "Case No: 700440",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Case Management Fixture.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Beverly Ann Sterry",
        citation: "Case No: 700026",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Fixture.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "MR A E Talukdar -v- TZG Partnerships",
        citation: "Case No: 699531",
        date: "",
        type: "",
        confidential: "",
        court: "London South Employment Tribunal",
        judge: "Employment Judge Balogun",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Olga Luscombe -v- Procurious Limited & Tania Seary",
        citation: "Case No: 696882",
        date: "",
        type: "",
        confidential: "",
        court: "Central London Employment Tribunal",
        judge: "Employment Judge C Sharp",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "N Gough -v- Board of Governers At Mount Grace School",
        citation: "Case No: 697467",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge Woffenden",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr T Field -v- ASDA Stores LTD",
        citation: "Case No: 695408",
        date: "",
        type: "",
        confidential: "",
        court: "Bristol Employment Tribunal",
        judge: "Employment Judge Smail",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Case Management Fixture.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Heather Barclay -v- ASDA Stores",
        citation: "Case No: 4105781/2022",
        date: "",
        type: "",
        confidential: "",
        court: "Manchester Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mark Forsyth Taylor -v- Redcentric Solutions Limited",
        citation: "Case No: 1804275/2023",
        date: "",
        type: "",
        confidential: "",
        court: "Before:",
        judge: "Employment Judge Deeley",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The claimant, Mr Mark Taylor, brought claims against Redcentric Solutions Limited for unpaid commission for February to April 2023 and wrongful dismissal regarding notice pay. The Tribunal found that the claimant was entitled to the commission payments, constituting unauthorised deductions from wages, but dismissed the wrongful dismissal claim as the respondent lawfully paid one week's notice in lieu during the claimant's probationary period.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr G Price -v- Fleet Express & Logistics Ltd",
        citation: "Case No: 1302825/2023",
        date: "",
        type: "",
        confidential: "",
        court: "West Midlands Employment Tribunal (by CVP)",
        judge: "Employment Judge Routley",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The key issue in Mr G Price v Fleet Express & Logistics Ltd was whether the claimant was unfairly dismissed following incidents involving alleged aggressive behavior towards his supervisor, Mr Pugh. The Tribunal found the claimant was unfairly dismissed but reduced the compensation by 75% due to contributory conduct, awarding the claimant £2,743.19.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Paul Andrew Whittaker -v- (1) Dogwoof Ltd (2) Anthony Tabatznik",
        citation: "Case No: 2205898/2022",
        date: "",
        type: "",
        confidential: "",
        court: "London Central Employment Tribunal",
        judge: "Employment Judge",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing (Video) to manage complex whistleblowing detriments.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Jan Godliman -v- London Borough of Waltham Forest",
        citation: "Case No: 3219922/2020",
        date: "",
        type: "",
        confidential: "",
        court: "East London Employment Tribunal",
        judge: "Employment Judge C Lewis",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Ms J Godliman brought claims against the London Borough of Waltham Forest alleging direct disability discrimination, discrimination arising from disability, harassment related to disability, and victimisation under the Equality Act 2010. The Tribunal dismissed the claims for direct disability discrimination and several complaints of discrimination and harassment following the Claimant's withdrawal, and found the remaining complaints and the victimisation claim to fail. Overall, all claims were dismissed.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "David Bannister -v- DPD Group UK Ltd",
        citation: "Case No: 3305117/2020",
        date: "",
        type: "",
        confidential: "",
        court: "Watford",
        judge: "Employment Judge Bedeau",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The claimant, Mr David Bannister, who suffered from multiple disabilities including learning difficulties and severe hearing impairment, brought claims against DPD Group UK Ltd for disability discrimination and failure to make reasonable adjustments following his dismissal for gross misconduct. The Tribunal found the disability discrimination and failure to make reasonable adjustments claims well-founded, with the dismissal linked to issues arising from his disabilities rather than unrelated misconduct.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mrs Nichola Pilgrim -v- Herefordshire and Worcestershire Health and Care NHS Trust",
        citation: "Case No: 1301189/2021",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Harrington",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing (Video) involving NHS Trust.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr D Austin -v- Kingspan Ltd",
        citation: "Case No: 1307462/2020",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham by CVP",
        judge: "Employment Judge Dean",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Mr D Austin, a disabled employee, was found to have been unfairly dismissed by Kingspan Ltd in breach of the Employment Rights Act 1996. Although he withdrew some discrimination claims under the Equality Act 2010, the Tribunal found that he was subjected to unlawful disability discrimination under section 15 and awarded him compensation totaling £33,008.27 for unfair dismissal and injury to feelings.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr C Borg-Neal -v- Lloyds Banking Group",
        citation: "Case No: 692828",
        date: "",
        type: "",
        confidential: "",
        court: "Video Hearing",
        judge: "Employment Judge Lewis",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Hearing Fixture.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Michael Lambrianos -v- Nowy Styl UK Limited",
        citation: "Case No: 2201870/2022",
        date: "",
        type: "",
        confidential: "",
        court: "London Central Employment Tribunal",
        judge: "Employment Judge Sutton",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The claimant, Mr Michael Lambrianos, brought a claim against Nowy Styl UK Limited for unpaid commission on multiple sales. The Tribunal found the respondent owed the claimant £716.40 in commission but refused both parties' applications for costs, noting the claimant's claim largely failed and the respondent's defense was reasonable and pragmatic.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Ismail Ismail -v- ASDA Stores Limited",
        citation: "Case No: 3302412/2022",
        date: "",
        type: "",
        confidential: "",
        court: "Watford",
        judge: "Employment Judge Din",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Mr Ismail Ismail claimed constructive unfair dismissal against Asda Stores Limited, alleging denial of promotion opportunities and bullying by a senior manager, Mr Preston, which breached the implied term of trust and confidence. The Employment Tribunal found that the claimant was not constructively dismissed and dismissed the claim.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr S Bridges -v- ASDA",
        citation: "Case No: 686538",
        date: "",
        type: "",
        confidential: "",
        court: "Wales Employment Tribunal",
        judge: "Employment Judge Harding",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr C Vassallo -v- Sizedwell Clothing Ltd",
        citation: "Ref: 3204026/2022",
        date: "",
        type: "",
        confidential: "",
        court: "East London Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (1 day).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ms V Parmar -v- John Lewis Plc",
        citation: "Case No: 688031",
        date: "",
        type: "",
        confidential: "",
        court: "London South Employment Tribunal",
        judge: "Employment Judge Beck",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr Danny Hazel & Mr Connor O'Driscoll -v- Lift Gear Engineering Limited",
        citation: "Case No: 687996",
        date: "",
        type: "",
        confidential: "",
        court: "East London Employment Tribunal",
        judge: "Employment Judge Shotter",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing for multiple claimants.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ms Shakila Devi Perumal -v- Cardiff University",
        citation: "Ref: 1601704/2021",
        date: "",
        type: "",
        confidential: "",
        court: "On:",
        judge: "Employment Judge S Knight",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "M Forbes-Innerarity –v- ASDA",
        citation: "Case No: 684315",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Alex Soyvural -v- Boots Uk Limted",
        citation: "Case No: 686401",
        date: "",
        type: "",
        confidential: "",
        court: "London South Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Video Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr J Seaman -v- Morrisons PLC",
        citation: "Case No: 682857",
        date: "",
        type: "",
        confidential: "",
        court: "Manchester Employment Tribunal",
        judge: "Employment Judge Shulman",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "B Mafavuke -v- Home-Start Birmingham North West",
        citation: "Case No: 682260",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "Employment Judge Faulkner",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing fixture.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Douglas Conroy",
        citation: "Case No: 674723",
        date: "",
        type: "",
        confidential: "",
        court: "London South Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Preliminary Hearing fixture.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Miss P Hill v Apex Jewellery",
        citation: "Case No: 686458",
        date: "",
        type: "",
        confidential: "",
        court: "Manchester Employment Tribunal",
        judge: "Employment Judge Loy",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Telephone Preliminary Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Gillian Oxborrow & Others -v- Partnerships In Care",
        citation: "Ref: 3300169/2017",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "Employment Judge Frances Eccles",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Adele Deane -v- Solihull Metropolitan Borough Council",
        citation: "Ref: 1307028/2020",
        date: "",
        type: "",
        confidential: "",
        court: "Birmingham Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing (4 days).",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr G Fuller -v- Lancashire County Council",
        citation: "Ref: 2414517/2021",
        date: "",
        type: "",
        confidential: "",
        court: "Manchester (hybrid (1st day) and",
        judge: "Employment Judge Mc",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The key issue in Mr G Fuller's claim against Lancashire County Council was whether he was an employee or a casual worker during the period when alleged unauthorised deductions from his wages were made. The tribunal found that the claimant was not an employee but a casual worker and dismissed the claim for unauthorised deductions. The respondent had ceased offering shifts during an investigation period, which was not considered an unlawful deduction of wages.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "N Lomotey v Mitie Limited",
        citation: "Ref: 2300279/2021",
        date: "",
        type: "",
        confidential: "",
        court: "London South Employment Tribunal (by CVP)",
        judge: "Employment Judge Kelly",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The key issue in this case was whether the claimant, Natasha Lomotey, was unfairly dismissed by Mitie Limited. The Employment Tribunal found in favor of the claimant, ruling that the dismissal was unfair and ordering a compensation payment of £12,000, with the proceedings adjourned to allow for settlement implementation.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr K Macleod -v- Mitie Group PLC",
        citation: "Ref: 3301008/2021",
        date: "",
        type: "",
        confidential: "",
        court: "Watford Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Samantha Zenda Ovies -v- Mahiul Muqit",
        citation: "Ref: 2200311/2021",
        date: "",
        type: "",
        confidential: "",
        court: "London Central Employment Tribunal",
        judge: "Employment Judge Davidson",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The case concerned Ms Samantha Zenda Ovies' claim of unfair dismissal by Mr Mahiul Muqit, her former employer. The Tribunal found that the dismissal was unfair, awarded the claimant one day's holiday pay, and ordered payment of an outstanding £2,000 gross bonus from June 2020. The Tribunal also allowed either party to apply for a remedy hearing to determine further compensation or remedies.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr G Tuffen v Asda Stores Limited",
        citation: "Case No: 686651",
        date: "",
        type: "",
        confidential: "",
        court: "East London Employment Tribunal",
        judge: "",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Final Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Andrew Hemming -v- Ellisa Motors Limited",
        citation: "Ref: 1303462/2021",
        date: "",
        type: "",
        confidential: "",
        court: "On:",
        judge: "Employment Judge Mensah",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "The claimant, Mr Andrew Hemming, brought claims against Ellisa Motors Limited for unpaid holiday pay, unfair dismissal, and redundancy. The tribunal found in favour of the claimant on the holiday pay claim, ordering the respondent to pay £1,843.80 for untaken accrued holiday. However, the claims for unfair dismissal and redundancy were dismissed.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Ms Devi Sundar -v- Cardiff University",
        citation: "Case No: 683848",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal",
        judge: "Employment Judge W Brady",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Ms D Sundar brought multiple claims against Cardiff University including unfair dismissal, detriments for protected disclosures, race, disability and marriage discrimination, breach of contract, and victimisation. After several preliminary hearings and amendment applications, all claims were dismissed by the Employment Tribunal, which found no evidence to support unfair dismissal, discrimination, victimisation, or breach of contract. The claimant was also found not to be disabled under the Equality Act 2010, resulting in dismissal of the reasonable adjustments claim.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Jhuti -v- Royal Mail Group Ltd",
        citation: "Case No: N/A",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Appeal Tribunal",
        judge: "Employment Judge Bax",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "EAT Appeal / Remission Hearing regarding high-profile whistleblowing claim.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mr D Kuma -v- ASDA Stores Limited",
        citation: "Case No: N/A",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal",
        judge: "Employment Judge Bax",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Employment Tribunal proceedings.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Mrs Z Mason -v- K V Hartshorne (Chemists) Limited",
        citation: "Case No: N/A",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal",
        judge: "Employment Judge Bax",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Employment Tribunal proceedings.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Shilen Mehta -v- Pomvom UK Limited",
        citation: "Case No: N/A",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal",
        judge: "Employment Judge Bax",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Employment Tribunal proceedings.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Carvell Appeal",
        citation: "Case No: N/A",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Appeal Tribunal",
        judge: "Employment Judge Bax",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Appeal Hearing.",
        significance: "",
        starred: false,
        key_case_law: []
    },
    {
        title: "Kaye Tranter -v- [Respondent]",
        citation: "Case No: N/A",
        date: "",
        type: "",
        confidential: "",
        court: "Employment Tribunal",
        judge: "Employment Judge Bax",
        solicitor: "",
        firm: "",
        client: "",
        leading: "",
        opposing: "",
        status: "",
        description: "Pre-Trial proceedings.",
        significance: "",
        starred: false,
        key_case_law: []
    }
];
